"""request_history_table

Revision ID: 57351c425fa7
Revises: 4b8047d1b9ab
Create Date: 2025-12-17 23:41:22.083311+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57351c425fa7'
down_revision: Union[str, Sequence[str], None] = '4b8047d1b9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_datetime', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('processing_time_ms', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', name='httpmethodenum', native_enum=False), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.BigInteger(), nullable=False),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('request_size_bytes', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_request_history_datetime', 'request_history', ['request_datetime'], unique=False)
    op.create_index('idx_request_history_endpoint', 'request_history', ['endpoint'], unique=False)
    op.create_index('idx_request_history_method', 'request_history', ['method'], unique=False)
    op.create_index('idx_request_history_status_code', 'request_history', ['status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_request_history_status_code', table_name='request_history')
    op.drop_index('idx_request_history_method', table_name='request_history')
    op.drop_index('idx_request_history_endpoint', table_name='request_history')
    op.drop_index('idx_request_history_datetime', table_name='request_history')
    op.drop_table('request_history')
    # ### end Alembic commands ###
