"""request_history_add_query_params

Revision ID: 9fca828d23d0
Revises: 57351c425fa7
Create Date: 2025-12-18 00:00:22.539155+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fca828d23d0'
down_revision: Union[str, Sequence[str], None] = '57351c425fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_history', sa.Column('query_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_history', 'query_params')
    # ### end Alembic commands ###
