"""stock_price_table

Revision ID: 108ecf49ea0d
Revises: 
Create Date: 2025-12-06 18:06:49.767536+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108ecf49ea0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('begin', sa.TIMESTAMP(), nullable=False),
    sa.Column('end', sa.TIMESTAMP(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'begin', name='unique_ticker_begin')
    )
    op.create_index('idx_stock_price_begin', 'stock_price', ['begin'], unique=False)
    op.create_index('idx_stock_price_ticker', 'stock_price', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_price_ticker', table_name='stock_price')
    op.drop_index('idx_stock_price_begin', table_name='stock_price')
    op.drop_table('stock_price')
    # ### end Alembic commands ###
