"""news_source_indexes

Revision ID: a30ebd948215
Revises: 0482ad69a50e
Create Date: 2026-05-30 00:08:48.854799+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30ebd948215'
down_revision: Union[str, Sequence[str], None] = '0482ad69a50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_news_article_source'), table_name='news_article')
    op.drop_index(op.f('idx_news_article_topic'), table_name='news_article')
    op.create_index('idx_news_article_source_published_at', 'news_article', ['source', 'published_at'], unique=False)
    op.create_index('idx_news_article_topic_published_at', 'news_article', ['topic', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_news_article_topic_published_at', table_name='news_article')
    op.drop_index('idx_news_article_source_published_at', table_name='news_article')
    op.create_index(op.f('idx_news_article_topic'), 'news_article', ['topic'], unique=False)
    op.create_index(op.f('idx_news_article_source'), 'news_article', ['source'], unique=False)
    # ### end Alembic commands ###
