"""news_article_enrichment

Revision ID: 9f558bc5b0fa
Revises: a30ebd948215
Create Date: 2026-05-30 10:33:33.992262+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f558bc5b0fa'
down_revision: Union[str, Sequence[str], None] = 'a30ebd948215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article_enrichment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('news_article_id', sa.BigInteger(), nullable=False),
    sa.Column('tickers', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('sector', sa.String(length=20), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_article.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_article_enrichment_article_created_at', 'news_article_enrichment', ['news_article_id', 'created_at'], unique=False)
    op.create_index('idx_news_article_enrichment_article_id', 'news_article_enrichment', ['news_article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_news_article_enrichment_article_id', table_name='news_article_enrichment')
    op.drop_index('idx_news_article_enrichment_article_created_at', table_name='news_article_enrichment')
    op.drop_table('news_article_enrichment')
    # ### end Alembic commands ###
