"""add_news_source_table

Revision ID: 0482ad69a50e
Revises: 9fca828d23d0
Create Date: 2026-05-29 22:55:07.757935+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0482ad69a50e'
down_revision: Union[str, Sequence[str], None] = '9fca828d23d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'published_at', name='unique_url_published_at')
    )
    op.create_index('idx_news_article_published_at', 'news_article', ['published_at'], unique=False)
    op.create_index('idx_news_article_source', 'news_article', ['source'], unique=False)
    op.create_index('idx_news_article_topic', 'news_article', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_news_article_topic', table_name='news_article')
    op.drop_index('idx_news_article_source', table_name='news_article')
    op.drop_index('idx_news_article_published_at', table_name='news_article')
    op.drop_table('news_article')
    # ### end Alembic commands ###
