"""add_sentiment_score

Revision ID: 64c79839e99a
Revises: 9f558bc5b0fa
Create Date: 2026-05-30 12:00:50.973409+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c79839e99a'
down_revision: Union[str, Sequence[str], None] = '9f558bc5b0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_article_enrichment', sa.Column('sentiment_score', sa.Float(), nullable=False))
    op.drop_index(op.f('idx_news_article_enrichment_article_created_at'), table_name='news_article_enrichment')
    op.drop_index(op.f('idx_news_article_enrichment_article_id'), table_name='news_article_enrichment')
    op.create_unique_constraint('uq_news_article_enrichment_article_id', 'news_article_enrichment', ['news_article_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_news_article_enrichment_article_id', 'news_article_enrichment', type_='unique')
    op.create_index(op.f('idx_news_article_enrichment_article_id'), 'news_article_enrichment', ['news_article_id'], unique=False)
    op.create_index(op.f('idx_news_article_enrichment_article_created_at'), 'news_article_enrichment', ['news_article_id', 'created_at'], unique=False)
    op.drop_column('news_article_enrichment', 'sentiment_score')
    # ### end Alembic commands ###
