TARGET_COLUMN = 'target_price_change'
DEFAULT_SEED = 42
DEFAULT_TICKER = 'SBER'
LSTM_EXPERIMENT_NAME = 'lstm_checkpoint'
CATBOOST_EXPERIMENT_NAME = 'catboost_checkpoint'
DEFAULT_EXPERIMENT_NAME = LSTM_EXPERIMENT_NAME
